const COLLEGE_MAP = {
  bca: "bachelor of computer applications",
  bsc: "bachelor of science",
  msc: "master of science",
  be: "bachelor of engineering",
  ba: "bachelor of arts",
  ma: "master of arts",
  ecommerce: "bachelor of commerce ecommerce",
  "e-commerce": "bachelor of commerce ecommerce",
  honors: "bachelor of commerce honors",
  "software development":
    "bachelor of vocation software development & e-commerce",
  "bvoc software": "bachelor of vocation software development & e-commerce",
  bvoc: "bachelor of vocation",
  banking: "bachelor of vocation banking & finance",
  finance: "bachelor of vocation banking & finance",
  bjmac: "bachelor of journalism and mass communication",
  bajmc: "bachelor of journalism and mass communication",
  bjmc: "bachelor of journalism and mass communication",
  bcom: "bachelor of commerce",
  mcom: "master of commerce",
  bba: "bachelor of business administration",
  "bba db": "bachelor of business administration in digital business",
  bed: "bachelor of education",
  diploma: "diploma course",
  mph: "master of public health course",
  mvoc: "master of vocation course",
  bph: "bachelor of public health course",
  adda: "advanced diploma in data analytics course",
  pgdrm: "post graduate diploma in retail management course",
  forensic: "certificate course in forensic science",
  ccfs: "certificate course in forensic science",
  blockchain: "certificate course in blockchain technology and applications",
  cbta: "certificate course in blockchain technology and applications",
  cs: "computer science department",
  cse: "computer science department",
  it: "information technology",
  hist: "history",
  maths: "mathematics",
  chem: "chemistry",
  accounts: "department of commerce",
  management: "management department",
  ped: "physical education department",
  anthro: "anthropology",
  politics: "political science",
  dept: "department",
  stats: "statistics department",
  statistics: "statistics department",
  mgmt: "management department",

  admn: "admission",
  adm: "admission",
  apply: "admission process",
  enroll: "admission",
  registration: "admission",
  register: "admission",
  cutoff: "cut off marks",
  merit: "merit list",
  counselling: "counselling process",
  seat: "seat availability",
  vacancy: "available seats",

  fee: "fees",
  fees: "fees",
  cost: "fees",
  price: "fees",
  charges: "fees",
  amount: "fees",
  kitna: "how much",
  "total fee": "fees structure",

  exam: "examination",
  test: "examination",
  "mid sem": "mid semester examination",
  "end sem": "end semester examination",
  final: "final examination",
  result: "examination result",
  back: "backlog examination",
  kt: "supplementary examination",
  internal: "internal assessment",
  practical: "practical examination",

  hod: "head of department",
  teacher: "faculty",
  maam: "ma'am",
  mam: "ma'am",
  prof: "professor",
  mr: "mr.",
  mrs: "mrs.",
  "miss.": "miss",
  ms: "ms.",
  lecturer: "faculty",
  staff: "college staff",

  library: "college library",
  hostel: "college hostel",
  canteen: "college canteen",
  bus: "college transport",
  transport: "college transport",
  lab: "laboratory",
  wifi: "campus wifi",
  placement: "placement cell",
  internship: "training and internship",

  att: "attendance",
  present: "attendance",
  absent: "attendance",
  marks: "marks",
  score: "marks",
  cgpa: "grade point average",
  sgpa: "semester grade point average",

  kab: "when",
  kaise: "how",
  kya: "what",
  kidhar: "where",
  timing: "time",
  duration: "course duration",
  eligibility: "eligibility criteria",
  syllabus: "course syllabus",
  prospectus: "college prospectus",

  "eligibility criteria": "eligibility",
  "eligible": "eligibility",
  "who can apply": "eligibility",

  "entrance": "entrance exam",
  "entrance exam": "entrance exam",
  "admission test": "entrance exam",

  "seats": "seat availability",
  "seat availability": "seat availability",
  "total seats": "seat availability",
  "intake": "seat availability",

  "deadline": "admission deadline",
  "last date": "admission deadline",
  "closing date": "admission deadline",
  "end date": "admission deadline",
  "when to apply": "admission deadline",
  "apply last date": "admission deadline",

    "फीस": "fees",
    "शुल्क": "fees",
    "पैसे": "money",
    "दाखिला": "admission",
    "प्रवेश": "admission",
    "सीटें": "seats",
    "सीट": "seat",
    "पात्रता": "eligibility",
    "योग्यता": "eligibility",
    "समय": "duration",
    "अवधि": "duration",
    "विभाग": "department",
    "शिक्षक": "faculty",
    "अध्यापक": "faculty",
    "नौकरी": "placement",
    "परीक्षा": "exam",
    "परिणाम": "result",
    "नतीजा": "result",
    "पुस्तकालय": "library",
    "किताब": "book",
    "कब": "when",
    "कहाँ": "where",
    "कैसे": "how",
    "कितना": "how much",
    "क्या": "what",
    "kitna": "how much",
    "kab": "when",
    "fees kitni hai": "fees structure",
    "admission kab hoga": "admission deadline",
    "seat kitni hai": "seat availability",
    "विभाग": "department",
    "संगणक": "computer science",
    "वाणिज्य": "commerce",
    "प्रबंधन": "management",
    "कला": "arts",
    "विज्ञान": "science",

    "पाठ्यक्रम": "course",
    "डिग्री": "degree",
    "प्रमाणपत्र": "certificate",
    "डिप्लोमा": "diploma",
    
    "बीका": "bca",
    "बीबीए": "bba",
    "बीकॉम": "bcom",
    "एमए": "ma",
    "बीसीए ":"bca",
    "पाठ्यक्रम":"course",
    "कोर्सेज":"course",

    "दाखिला": "admission",
    "प्रवेश": "admission",
    "सीटें": "seats",
    "जगह": "seats",
    "पात्रता": "eligibility",
    "योग्यता": "eligibility",
    "अंतिम तिथि": "deadline",
    
    "शिक्षक": "faculty",
    "अध्यापक": "faculty",
    "प्रोफेसर": "professor",
    "गुरु": "teacher",
    "शिक्षक वर्ग":"faculty",

    "नियुक्ति":"placement",

    "pathyakram": "course",
  "pathyakramon": "courses",
  "shiksha": "education",
  "kaksha": "class",
  "snatak": "bachelor",
  "parsnatak": "master",
  "degree": "degree",
  "parmanpatra": "certificate",
  "parman patra": "certificate",

  "dakhila": "admission",
  "pravesh": "admission",
  "bharti": "admission",
  "apply kaise kare": "admission process",
  "patrata": "eligibility",
  "yogyata": "eligibility",
  "kaun apply kar sakta hai": "eligibility",
  "shartein": "criteria",
  "antim tithi": "deadline",
  "akhiri tarikh": "deadline",
  "last date kya hai": "deadline",

  "shulk": "fees",
  "paisa": "fees",
  "paise": "fees",
  "kitna paisa": "fees",
  "kharcha": "fees",
  "kimat": "fees",
  "fees kitni hai": "fees structure",
  "kitne paise lagenge": "fees",

  "sthan": "seats",
  "jagah": "seats",
  "kitni jagah hai": "seat availability",
  "seetein": "seats",
  "seat kitni hai": "seat availability",

  "shikshak": "faculty",
  "adhyapak": "faculty",
  "guru": "teacher",
  "shikshak varg": "faculty",
  "vibhag": "department",
  "adhyaksh": "head of department",

  "naukri": "placement",
  "niyukti": "placement",
  "kam": "work",
  "salary kitni milti hai": "placement package",
  "company aati hai": "placement",

  "pariksha": "exam",
  "imtihan": "exam",
  "natija": "result",
  "parinam": "result",
  "ank": "marks",
  "number": "marks",
  "pass": "pass",
  "fail": "fail",

  "pustakalaya": "library",
  "kitab": "book",
  "pustak": "book",
  "hostel": "hostel",
  "khana": "canteen",
  "bus": "transport",
  "vahan": "transport",

  "kab": "when",
  "kahan": "where",
  "kidhar": "where",
  "kaise": "how",
  "kya": "what",
  "kyun": "why",
  "kitna": "how much",
  "kaun": "who",
  "kiska": "whose",
  "kab tak": "deadline",

  "प्रवेश": "admission",
  "दाखिला": "admission",
  "शुल्क": "fees",
  "फीस": "fees",
  "पात्रता": "eligibility",
  "योग्यता": "eligibility",
  "सीटें": "seats",
  "अंतिम तिथि": "deadline",
  "आखिरी तारीख": "deadline",
  "पाठ्यक्रम": "course",
  "विभाग": "department",
  "शिक्षक": "faculty",
  "अध्यापक": "faculty",
  "नौकरी": "placement",
  "नियुक्ति": "placement",
  "परीक्षा": "exam",
  "परिणाम": "result",
  "नतीजा": "result",
  "पुस्तकालय": "library",
  "किताब": "book",
  "संगणक": "computer science",
  "वाणिज्य": "commerce",
  "प्रबंधन": "management",
  "कला": "arts",
  "विज्ञान": "science",
  "स्नातक": "bachelor",
  "सर":"sir",
  "स्नातकोत्तर": "master",
  college: "college",
institute: "college",
campus: "college",
university: "university",
vidyalaya: "college",
mahavidyalaya: "college",
form: "admission form",
application: "admission",
"application form": "admission form",
"online form": "admission form",
"offline form": "admission form",
documents: "admission documents",
document: "admission documents",
"certificate required": "admission documents",
date: "deadline",
"important date": "deadline",
schedule: "deadline",
timeline: "deadline",
"college":"npgc",
"adress":"address",
"addres":"address",
"kab tak apply": "admission deadline",
"form kab band hoga": "admission deadline",
"nationl post graduate college":"npgc",
"national p.g.":"npgc",
"national pg":"npgc",
"national college":"npgc",
"कॉलेज के बारे में": "about college",
"कॉलेज की जानकारी": "about college",
"कॉलेज परिचय": "about college",
"कॉलेज का परिचय": "about college",
"कॉलेज प्रोफाइल": "about college",
"कॉलेज विवरण": "about college",
"कॉलेज की डिटेल": "about college",
"कॉलेज की पूरी जानकारी": "about college",
"कॉलेज का इतिहास": "about college",
"कॉलेज के बारे में बताइए": "about college",
"npgc के बारे में": "about college",
"इस कॉलेज के बारे में": "about college",
"कॉलेज का पता": "college address",
"कॉलेज पता": "college address",
"कॉलेज कहाँ है": "college address",
"कॉलेज कहां स्थित है": "college address",
"कॉलेज की लोकेशन": "college address",
"कॉलेज का स्थान": "college address",
"कॉलेज कैसे पहुँचे": "college address",
"कॉलेज कैसे जाएँ": "college address",
"कॉलेज का रास्ता": "college address",
"कॉलेज का नक्शा": "college address",
"npgc का पता": "college address",
"कॉलेज का नंबर": "college contact",
"कॉलेज फोन नंबर": "college_contact",
"कॉलेज का मोबाइल नंबर": "college contact",
"कॉलेज संपर्क": "college contact",
"कॉलेज से संपर्क करें": "college contact",
"कॉलेज की ईमेल": "college contact",
"कॉलेज का ईमेल आईडी": "college contact",
"कॉलेज हेल्पलाइन": "college contact",
"कॉलेज कार्यालय नंबर": "college contact",
"npgc का संपर्क नंबर": "college contact",
"कॉलेज का समय": "college timings",
"कॉलेज की टाइमिंग": "college timings",
"कॉलेज कब खुलता है": "college timings",
"कॉलेज कब बंद होता है": "college timings",
"कॉलेज खुलने का समय": "college timings",
"कॉलेज बंद होने का समय": "college timings",
"कॉलेज का टाइम": "college timings",
"कॉलेज के काम करने का समय": "college timings",
"ऑफिस टाइम": "college timings",
"कॉलेज किस यूनिवर्सिटी से जुड़ा है": "college affiliation",
"कॉलेज किस विश्वविद्यालय से सम्बद्ध है": "college affiliation",
"कॉलेज की यूनिवर्सिटी": "college affiliation",
"कॉलेज किस यूनिवर्सिटी के अंतर्गत है": "college affiliation",
"npgc किस यूनिवर्सिटी से जुड़ा है": "college affiliation",
"कॉलेज की मान्यता": "college affiliation",
"ugc से मान्यता": "college affiliation",
"कॉलेज सरकारी है या प्राइवेट": "college type",
"कॉलेज सरकारी है": "college type",
"कॉलेज प्राइवेट है": "college type",
"npgc सरकारी है": "college type",
"npgc प्राइवेट है": "college type",
"कॉलेज का प्रकार": "college type",
"कॉलेज का स्वामित्व": "college type",
"कॉलेज सहायता प्राप्त है": "college type",
"एनपीजीसी": "npgc",
"एन पी जी सी": "npgc",
"एन.पी.जी.सी": "npgc",
"एनपी जी सी": "npgc",
"नेशनल पोस्ट ग्रेजुएट कॉलेज": "national post graduate college",
"नेशनल पोस्ट ग्रेजुएट कालेज": "national post graduate college",
"नेशनल पोस्ट ग्रैजुएट कॉलेज": "national post graduate college",
"राष्ट्रीय पोस्ट ग्रेजुएट कॉलेज": "national post graduate college",
"नेशनल पीजी कॉलेज": "national post graduate college",
"एनपीजी कॉलेज": "national post graduate college",
"एन पी जी कॉलेज": "national post graduate college",
"एन.पी.जी. कॉलेज": "national post graduate college",
"पोस्ट ग्रेजुएट कॉलेज": "national post graduate college",
"पीजी कॉलेज": "national post graduate college",
"पी जी कॉलेज": "national post graduate college",
"पी.जी. कॉलेज": "national post graduate college",
"एनपीजीसी कॉलेज": "national post graduate college"
};

module.exports = {COLLEGE_MAP};
