const VOCAB = [  // Core Entities & Tables
  "student",
  "fees",
  "marks",
  "attendance",
  "exam",
  "course",
  "courses",
  "program",
  "programme",
  "faculty",
  "hostel",
  "subject",
  "subjects",
  "duration",
  "major",
  "minor",
  "vocational",
  "certification",
  "undergraduate",
  "postgraduate",
  "diploma",
  "department",
  "guardian",
  "gender",
  "library",
  "scholarship",
  "placement",
  "canteen",
  "sports",
  "event",
  "campus", // Academic & Evaluation
  "test",
  "score",
  "result",
  "percentage",
  "grades",
  "report",
  "timetable",
  "schedule",
  "semester",
  "session",
  "class",
  "room",
  "professor",
  "teacher",
  "teaches",
  "syllabus",
  "unit",
  "internal",
  "external",
  "backpaper", // Admission & Deadlines
  "admission",
  "apply",
  "form",
  "status",
  "procedure",
  "closing date",
  "admission deadline",
  "when to apply",
  "process",
  "register",
  "deadline",
  "last date",
  "cut off",
  "merit",
  "eligibility",
  "document",
  "verification",
  "allotment",
  "seat",
  "vacancy",
  "cancellation",
  "withdraw",
  "prospectus",
  "guideline",

  // Facilities & Life
  "wifi",
  "gym",
  "mess",
  "food",
  "non-ac",
  "library card",
  "book",
  "issue",
  "return",
  "placement cell",
  "interview",
  "company",
  "package",
  "salary",
  "fest",
  "cultural",
  "tournament",
  "ground",
  "infrastructure",

  // Slang, Synonyms & Helpers
  "money",
  "cost",
  "price",
  "pay",
  "due",
  "balance",
  "who",
  "where",
  "how",
  "what",
  "when",
  "contact",
  "office",
  "help",
  "support",
  "location",

  // Teacher
  "manages",
  "head",
  "sir",
  "ma'am",
  "mr.",
  "mrs.",
  "miss",
  "ms.",

  // Admission – Extended
  "eligibility criteria",
  "eligible",
  "entrance",
  "entrance exam",
  "admission test",
  "seat availability",
  "total seats",
  "intake",
  'about college',
  'about npgc',
  'college background',
  'college profile',
  'college introduction',
  'npgc college',
  'college overview',
  'college information',
  'college details',
  'npgc college',
  'npgc details',
  'college details',
  'college address',
  'npgc address',
  'where is college',
  'where is npgc',
  'college location',
  'college situated',
  'college landmark',
  'college area',
  'college map',
  'how to reach college',
  'college contact',
  'college number',
  'college phone number',
  'college email',
  'npgc contact',
  'how to contact college',
  'college helpline',
  'college enquiry number',
  'college office contact',
  'college time',
  'college timings',
  'college opening time',
  'college closing time',
  'working hours',
  'college hours',
  'when does college open',
  'when does college close',
  'college schedule',
  'college affiliation',
  'which university',
  'npgc affiliated',
  'affiliated university',
  'college under which university',
  'government or private',
  'college type',
  'npgc type',
  'is npgc private',
  'is college private',
  'is college government',
  'is npgc government',
  'college ownership',
  "address"
];

const EmbeddingService = {
  generateEmbedding: (text) => {
    const input = text.toLowerCase();
    return VOCAB.map((word) => (input.includes(word) ? 1.0 : 0.0));
  },

  calculateSimilarity: (vecA, vecB) => {
    if (vecA.length !== vecB.length) return 0;

    let dotProduct = 0,
      normA = 0,
      normB = 0;
    for (let i = 0; i < vecA.length; i++) {
      dotProduct += vecA[i] * vecB[i];
      normA += vecA[i] ** 2;
      normB += vecB[i] ** 2;
    }
    if (normA === 0 || normB === 0) return 0;
    return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
  },
};

module.exports = EmbeddingService;
